### PR TITLE
Python version 3.5 has removed from supported

### PR DESCRIPTION
**Pull request by MaxTyulin**
## What do these changes do?
Python version 3.5 has removed from supported

## Related issue number
#144 

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by Arfey** [comment]
thx for your contribution 👍

**Comment by Arfey** [comment]
https://github.com/aio-libs/create-aio-app/blob/master/CONTRIBUTING.md

don't forget add your name to list of contributors

**Comment by webknjaz** [comment]
`setup()` call also needs `python_version='>=3.6'` to be specified so that Pip wouldn't try to install the unsupported dists

**Comment by MaxTyulin** [comment]
Yeap, PR #146

**Pull request merged**
