### PR TITLE
docker image optimized

### PR DESCRIPTION
**Pull request by amenezes**
## What do these changes do?
The docker image size will be optimized from `~1 GB` to `~370 MB`.

## Related issue number
feature `improvement`

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by Arfey** [comment]
Hi. Thx for your contribute. I'm not sure that 1gb is so big deal. We talk about local development and in this case size is not so important.

`python:3.7` - nested from `debian` and have a lot of helpful tools for develop as ps etc.

what do u think about that?

**Comment by amenezes** [comment]
Hello @Arfey,

The docker image `python:3.7-slim` also have debian as [base](https://github.com/docker-library/python/blob/052eee2625b08d678cd58c71abaad0886a32d4ea/3.7/buster/slim/Dockerfile#L7). Then any additional package can be easily included via `apt-get`, for example.

Generally what I have seen and used when developing with containers is that we try to generate an minimal image as possible, in addition to trying to balance an easily use with security features.

Here's a comparison of known vulnerabilities between the two images:
- python:3.7: https://scan.vulnerablecontainers.org/scan?name=python:3.7 [**107**]
- python:3.7-slim: https://scan.vulnerablecontainers.org/scan?name=python:3.7-slim [**4**]

**Comment by Arfey** [comment]
Vulnerabilities it's okey but how does it connected with local development?
Debian slim don't have helpful utils.

Screenshot 2020-02-24 at 21 37 35

Yes we can install this tools but maybe someone use something else. I think that default (not minimised) debian it's much comfortably.

**Comment by amenezes** [comment]
Sorry, I think I got confused :sweat_smile:

Maybe because I saw on the template page the [docker-compose.production.yml](https://github.com/aio-libs/create-aio-app/blob/master/create_aio_app/template/%7B%7Bcookiecutter.project_name%7D%7D/docker-compose.production.yml) file and a [build target](https://github.com/aio-libs/create-aio-app/blob/master/create_aio_app/template/%7B%7Bcookiecutter.project_name%7D%7D/Makefile#L20) on Makefile and thought that the development flow and deploy of the image generated by the template would be unique.

Is because the development image that I use it's the same to other stages changing only the application config. But that's not the case here right?

Perhaps the `docker-compose.production.yml` file could be renamed to `docker-compose.develop.yml` just to make it more explicit that the container image is for use in a development environment only.

Thanks for your super fast feedback.

**Comment by Arfey** [comment]
Yeh. I think that we can remove `docker-compose.production.yml` and make command which connected with that.

We added it for use docker [swarm](https://docs.docker.com/compose/production/) for production but probably it was not good idea.

So, if u wanna do some contribute u can remove that 😀

ps: don't forget add yourself to `CONTRIBUTORS.txt`.

**Comment by amenezes** [comment]
Ok @Arfey I will do that.

**Pull request closed without merging**
