### PR TITLE
fix: removed ref `modindex`

### PR DESCRIPTION
**Pull request by Exs1de**
## What do these changes do?

Removed reference to py-modindex.html, which causes 404 error.

## Are there changes in behavior for the user?
No.

## Related issue number

#101 
## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by Arfey** [comment]
Good job. Thx 👍

**Comment by webknjaz** [comment]
@Arfey це костиль. правильно було б генерувати сторінки модулів)

**Comment by Arfey** [comment]
no page no problems :)

**Comment by webknjaz** [comment]
And no ability to link objects in source like ```
:py:func:`mod.func_name`
```

**Pull request merged**
